name: terminal-assistant
dependencies:
    - pip:
        - pip
        - gTTS
        - openai
        - pydub
        - requests
        - speechrecognition
        - keyboard
        - pyaudio
        - pylama
        - prospector
        - mypy