# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        wget http://files.portaudio.com/archives/pa_stable_v190700_20210406.tgz; tar -xvvf pa_stable_v190700_20210406.tgz; cd portaudio; ./configure; make; sudo make install
        cd /home/runner/work/terminal-assistant/terminal-assistant
        python3.10 -m pip install --upgrade pip setuptools wheel
        python3.10 -m pip install flake8 pytest
        python3.10 -m pip install openai==0.27.8 pyaudio==0.2.13 gtts==2.3.2 speechrecognition==3.10.0 keyboard==0.13.5 requests==2.31.0 
    - name: Lint with flake8
      run: |
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
